### ISSUE TITLE
Сборка Linux-версии

### ISSUE THREAD

**Issue by Dr-Hex** [viordash/ShareClipbrd#28]
Здравствуйте!
Не могли бы вы дать небольшое пояснение, как или какой командой осуществлялась сборка под Linux?

**Comment by viordash** [comment]
Добрый день,
в https://github.com/viordash/ShareClipbrd/blob/main/.github/workflows/dotnet.yml указаны команды для сборки обеих ОС. В частности для линукса:

- dotnet restore ./ShareClipbrd/ShareClipbrd.sln
- dotnet build ./ShareClipbrd/ShareClipbrd.sln --no-restore 
- dotnet publish "./ShareClipbrd/ShareClipbrdApp/ShareClipbrdApp.csproj" -c PublishRelease -r linux-x64 -f net7.0 -p:PublishSingleFile=true --self-contained false -o "./out/_linux64" -p:DebugType=None

**Comment by Dr-Hex** [comment]
Спасибо.
